"""change full-text to array sentences in wrtingSession

Revision ID: dbedd75179c3
Revises: e0285054b23e
Create Date: 2025-11-07 07:48:52.342330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbedd75179c3'
down_revision: Union[str, Sequence[str], None] = 'e0285054b23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_favorite_videos_user_youtube'), 'user_favorite_videos', type_='unique')
    op.add_column('writing_sessions', sa.Column('vietnamese_sentences', postgresql.ARRAY(sa.Text()), nullable=True))
    op.drop_column('writing_sessions', 'vietnamese_text')
    op.drop_column('writing_sessions', 'current_sentence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_sessions', sa.Column('current_sentence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('writing_sessions', sa.Column('vietnamese_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('writing_sessions', 'vietnamese_sentences')
    op.create_unique_constraint(op.f('uq_user_favorite_videos_user_youtube'), 'user_favorite_videos', ['user_id', 'youtube_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
