"""add user_online_status table

Revision ID: 63f168f827c8
Revises: 7d6cd8f642f1
Create Date: 2025-10-04 10:22:07.894468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f168f827c8'
down_revision: Union[str, Sequence[str], None] = '7d6cd8f642f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learning_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_sessions_pkey'))
    )
    op.create_index(op.f('learning_sessions_id_idx'), 'learning_sessions', ['id'], unique=False)
    op.create_index(op.f('learning_sessions_session_end_idx'), 'learning_sessions', ['session_end'], unique=False)
    op.create_index(op.f('learning_sessions_session_start_idx'), 'learning_sessions', ['session_start'], unique=False)
    op.create_index(op.f('learning_sessions_user_id_idx'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('user_online_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_online_status_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_online_status_pkey')),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_online_status_user_date')
    )
    op.create_index(op.f('user_online_status_date_idx'), 'user_online_status', ['date'], unique=False)
    op.create_index(op.f('user_online_status_id_idx'), 'user_online_status', ['id'], unique=False)
    op.create_index(op.f('user_online_status_user_id_idx'), 'user_online_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_online_status_user_id_idx'), table_name='user_online_status')
    op.drop_index(op.f('user_online_status_id_idx'), table_name='user_online_status')
    op.drop_index(op.f('user_online_status_date_idx'), table_name='user_online_status')
    op.drop_table('user_online_status')
    op.drop_index(op.f('learning_sessions_user_id_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_session_start_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_session_end_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_id_idx'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
