"""add translation_sentence

Revision ID: 45ec66c82d4c
Revises: fd89e0c3c16b
Create Date: 2025-11-25 22:07:05.591310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ec66c82d4c'
down_revision: Union[str, Sequence[str], None] = 'fd89e0c3c16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_chat_messages', sa.Column('translation_sentence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaking_chat_messages', 'translation_sentence')
    # ### end Alembic commands ###
