"""update streak

Revision ID: 86576ec0ac41
Revises: b49ec3947d7e
Create Date: 2025-12-03 21:41:14.206214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86576ec0ac41'
down_revision: Union[str, Sequence[str], None] = 'b49ec3947d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('login_streaks_date_idx'), table_name='login_streaks')
    op.drop_constraint(op.f('uq_login_streak_user_date'), 'login_streaks', type_='unique')
    op.create_unique_constraint('uq_login_streak_user', 'login_streaks', ['user_id'])
    op.drop_column('login_streaks', 'date')
    op.drop_column('login_streaks', 'login_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_streaks', sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('login_streaks', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_login_streak_user', 'login_streaks', type_='unique')
    op.create_unique_constraint(op.f('uq_login_streak_user_date'), 'login_streaks', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('login_streaks_date_idx'), 'login_streaks', ['date'], unique=False)
    # ### end Alembic commands ###
