"""add table for solo study

Revision ID: 9be3114086a2
Revises: b615fed74cdf
Create Date: 2025-10-25 06:36:14.889087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be3114086a2'
down_revision: Union[str, Sequence[str], None] = 'b615fed74cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_video_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('background_video_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('background_video_types_name_key'))
    )
    op.create_index(op.f('background_video_types_id_idx'), 'background_video_types', ['id'], unique=False)
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sound_file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sounds_pkey'))
    )
    op.create_index(op.f('sounds_id_idx'), 'sounds', ['id'], unique=False)
    op.create_table('background_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['background_video_types.id'], name=op.f('background_videos_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('background_videos_pkey'))
    )
    op.create_index(op.f('background_videos_id_idx'), 'background_videos', ['id'], unique=False)
    op.create_table('session_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', name='sessiongoalsstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('session_goals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('session_goals_pkey'))
    )
    op.create_index(op.f('session_goals_id_idx'), 'session_goals', ['id'], unique=False)
    op.create_index(op.f('session_goals_user_id_idx'), 'session_goals', ['user_id'], unique=False)
    op.create_table('user_favorite_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_url', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_favorite_videos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_favorite_videos_pkey'))
    )
    op.create_index(op.f('user_favorite_videos_id_idx'), 'user_favorite_videos', ['id'], unique=False)
    op.create_index(op.f('user_favorite_videos_user_id_idx'), 'user_favorite_videos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_favorite_videos_user_id_idx'), table_name='user_favorite_videos')
    op.drop_index(op.f('user_favorite_videos_id_idx'), table_name='user_favorite_videos')
    op.drop_table('user_favorite_videos')
    op.drop_index(op.f('session_goals_user_id_idx'), table_name='session_goals')
    op.drop_index(op.f('session_goals_id_idx'), table_name='session_goals')
    op.drop_table('session_goals')
    op.drop_index(op.f('background_videos_id_idx'), table_name='background_videos')
    op.drop_table('background_videos')
    op.drop_index(op.f('sounds_id_idx'), table_name='sounds')
    op.drop_table('sounds')
    op.drop_index(op.f('background_video_types_id_idx'), table_name='background_video_types')
    op.drop_table('background_video_types')
    # ### end Alembic commands ###
