"""Add learning path tables final

Revision ID: 518d82311c75
Revises: 6a5c5db4057e
Create Date: 2025-12-22 06:39:48.650119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518d82311c75'
down_revision: Union[str, Sequence[str], None] = '6a5c5db4057e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learning_paths_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_paths_pkey'))
    )
    op.create_index(op.f('learning_paths_id_idx'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('learning_paths_user_id_idx'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('daily_lesson_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], name=op.f('daily_lesson_plans_learning_path_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_lesson_plans_pkey')),
    sa.UniqueConstraint('learning_path_id', 'day_number', name='_learning_day_uc')
    )
    op.create_index(op.f('daily_lesson_plans_id_idx'), 'daily_lesson_plans', ['id'], unique=False)
    op.create_index(op.f('daily_lesson_plans_learning_path_id_idx'), 'daily_lesson_plans', ['learning_path_id'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_lesson_plan_id', sa.Integer(), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['daily_lesson_plan_id'], ['daily_lesson_plans.id'], name=op.f('user_lesson_progress_daily_lesson_plan_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_lesson_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_lesson_progress_pkey')),
    sa.UniqueConstraint('user_id', 'daily_lesson_plan_id', 'lesson_index', name='_user_lesson_progress_uc')
    )
    op.create_index(op.f('user_lesson_progress_daily_lesson_plan_id_idx'), 'user_lesson_progress', ['daily_lesson_plan_id'], unique=False)
    op.create_index(op.f('user_lesson_progress_id_idx'), 'user_lesson_progress', ['id'], unique=False)
    op.create_index(op.f('user_lesson_progress_user_id_idx'), 'user_lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_lesson_progress_user_id_idx'), table_name='user_lesson_progress')
    op.drop_index(op.f('user_lesson_progress_id_idx'), table_name='user_lesson_progress')
    op.drop_index(op.f('user_lesson_progress_daily_lesson_plan_id_idx'), table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index(op.f('daily_lesson_plans_learning_path_id_idx'), table_name='daily_lesson_plans')
    op.drop_index(op.f('daily_lesson_plans_id_idx'), table_name='daily_lesson_plans')
    op.drop_table('daily_lesson_plans')
    op.drop_index(op.f('learning_paths_user_id_idx'), table_name='learning_paths')
    op.drop_index(op.f('learning_paths_id_idx'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
