"""Add speaking module with string fields

Revision ID: 5866a4774f30
Revises: d7537dcaf4c2
Create Date: 2025-10-25 06:52:35.289731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5866a4774f30'
down_revision: Union[str, Sequence[str], None] = 'd7537dcaf4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('speaking_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaking_sessions_pkey'))
    )
    op.create_index(op.f('speaking_sessions_difficulty_idx'), 'speaking_sessions', ['difficulty'], unique=False)
    op.create_index(op.f('speaking_sessions_id_idx'), 'speaking_sessions', ['id'], unique=False)
    op.create_index(op.f('speaking_sessions_user_id_idx'), 'speaking_sessions', ['user_id'], unique=False)
    op.create_table('speaking_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vietnamese_content', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['speaking_sessions.id'], name=op.f('speaking_chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaking_chat_messages_pkey'))
    )
    op.create_index(op.f('speaking_chat_messages_id_idx'), 'speaking_chat_messages', ['id'], unique=False)
    op.create_index(op.f('speaking_chat_messages_session_id_idx'), 'speaking_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('speaking_chat_messages_session_id_idx'), table_name='speaking_chat_messages')
    op.drop_index(op.f('speaking_chat_messages_id_idx'), table_name='speaking_chat_messages')
    op.drop_table('speaking_chat_messages')
    op.drop_index(op.f('speaking_sessions_user_id_idx'), table_name='speaking_sessions')
    op.drop_index(op.f('speaking_sessions_id_idx'), table_name='speaking_sessions')
    op.drop_index(op.f('speaking_sessions_difficulty_idx'), table_name='speaking_sessions')
    op.drop_table('speaking_sessions')
    # ### end Alembic commands ###
