"""fix_dictionary_indexes

Revision ID: ab82117cb655
Revises: bf86fc3ed07c
Create Date: 2025-09-13 19:37:10.953242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab82117cb655'
down_revision: Union[str, Sequence[str], None] = 'bf86fc3ed07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_definitions'), table_name='dictionary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dictionary_definitions'), 'dictionary', ['definitions'], unique=False)
    # ### end Alembic commands ###
