"""remove normalize_text

Revision ID: 920d11e66b6d
Revises: 8050dba75781
Create Date: 2025-11-21 22:08:06.703923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920d11e66b6d'
down_revision: Union[str, Sequence[str], None] = '8050dba75781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'normalized_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('normalized_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
