"""deletedAt

Revision ID: b25cea32c425
Revises: 20a16b4fbe4b
Create Date: 2025-09-29 21:25:48.171370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25cea32c425'
down_revision: Union[str, Sequence[str], None] = '20a16b4fbe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('password_reset_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('post_likes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('posts', 'deleted_at')
    op.drop_column('post_likes', 'deleted_at')
    op.drop_column('password_reset_tokens', 'deleted_at')
    op.drop_column('dictionary', 'deleted_at')
    # ### end Alembic commands ###
