"""remove_streak_count_from_login_streak_daily_v2

Revision ID: ff599414193c
Revises: 86576ec0ac41
Create Date: 2025-12-04 03:05:48.947655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff599414193c'
down_revision: Union[str, Sequence[str], None] = '86576ec0ac41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_streak_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streak_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['streak_id'], ['login_streaks.id'], name=op.f('login_streak_daily_streak_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_streak_daily_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('login_streak_daily_pkey')),
    sa.UniqueConstraint('user_id', 'date', name='uq_login_streak_daily_user_date')
    )
    op.create_index(op.f('login_streak_daily_date_idx'), 'login_streak_daily', ['date'], unique=False)
    op.create_index(op.f('login_streak_daily_id_idx'), 'login_streak_daily', ['id'], unique=False)
    op.create_index(op.f('login_streak_daily_streak_id_idx'), 'login_streak_daily', ['streak_id'], unique=False)
    op.create_index(op.f('login_streak_daily_user_id_idx'), 'login_streak_daily', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('login_streak_daily_user_id_idx'), table_name='login_streak_daily')
    op.drop_index(op.f('login_streak_daily_streak_id_idx'), table_name='login_streak_daily')
    op.drop_index(op.f('login_streak_daily_id_idx'), table_name='login_streak_daily')
    op.drop_index(op.f('login_streak_daily_date_idx'), table_name='login_streak_daily')
    op.drop_table('login_streak_daily')
    # ### end Alembic commands ###
