"""add field for speaki module

Revision ID: 8050dba75781
Revises: dbedd75179c3
Create Date: 2025-11-20 05:06:00.902479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8050dba75781'
down_revision: Union[str, Sequence[str], None] = 'dbedd75179c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_chat_messages', sa.Column('is_audio', sa.Boolean(), nullable=False))
    op.drop_column('speaking_chat_messages', 'vietnamese_content')
    op.add_column('speaking_sessions', sa.Column('my_character', sa.String(length=255), nullable=False))
    op.add_column('speaking_sessions', sa.Column('ai_character', sa.String(length=255), nullable=False))
    op.add_column('speaking_sessions', sa.Column('scenario', sa.Text(), nullable=False))
    op.alter_column('speaking_sessions', 'level',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('speaking_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('speaking_sessions_level_idx'), table_name='speaking_sessions')
    op.drop_column('speaking_sessions', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_sessions', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('speaking_sessions_level_idx'), 'speaking_sessions', ['level'], unique=False)
    op.alter_column('speaking_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('speaking_sessions', 'level',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.drop_column('speaking_sessions', 'scenario')
    op.drop_column('speaking_sessions', 'ai_character')
    op.drop_column('speaking_sessions', 'my_character')
    op.add_column('speaking_chat_messages', sa.Column('vietnamese_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('speaking_chat_messages', 'is_audio')
    # ### end Alembic commands ###
