"""update online

Revision ID: b49ec3947d7e
Revises: a19f54735d86
Create Date: 2025-12-03 21:25:43.608426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49ec3947d7e'
down_revision: Union[str, Sequence[str], None] = 'a19f54735d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('learning_sessions_id_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_session_end_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_session_start_idx'), table_name='learning_sessions')
    op.drop_index(op.f('learning_sessions_user_id_idx'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('session_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learning_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_sessions_pkey'))
    )
    op.create_index(op.f('learning_sessions_user_id_idx'), 'learning_sessions', ['user_id'], unique=False)
    op.create_index(op.f('learning_sessions_session_start_idx'), 'learning_sessions', ['session_start'], unique=False)
    op.create_index(op.f('learning_sessions_session_end_idx'), 'learning_sessions', ['session_end'], unique=False)
    op.create_index(op.f('learning_sessions_id_idx'), 'learning_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
