"""Add writing practice tables

Revision ID: 17fc2130231f
Revises: d31f7694564f
Create Date: 2025-10-20 20:14:31.712655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fc2130231f'
down_revision: Union[str, Sequence[str], None] = 'd31f7694564f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('total_sentences', sa.Integer(), nullable=False),
    sa.Column('current_sentence_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=True),
    sa.Column('vietnamese_text', sa.Text(), nullable=False),
    sa.Column('current_sentence', sa.Text(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('writing_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('writing_sessions_pkey'))
    )
    op.create_index(op.f('writing_sessions_id_idx'), 'writing_sessions', ['id'], unique=False)
    op.create_index(op.f('writing_sessions_user_id_idx'), 'writing_sessions', ['user_id'], unique=False)
    op.create_table('writing_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=True),
    sa.Column('evaluation_data', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['writing_sessions.id'], name=op.f('writing_chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('writing_chat_messages_pkey'))
    )
    op.create_index(op.f('writing_chat_messages_id_idx'), 'writing_chat_messages', ['id'], unique=False)
    op.create_index(op.f('writing_chat_messages_session_id_idx'), 'writing_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('writing_chat_messages_session_id_idx'), table_name='writing_chat_messages')
    op.drop_index(op.f('writing_chat_messages_id_idx'), table_name='writing_chat_messages')
    op.drop_table('writing_chat_messages')
    op.drop_index(op.f('writing_sessions_user_id_idx'), table_name='writing_sessions')
    op.drop_index(op.f('writing_sessions_id_idx'), table_name='writing_sessions')
    op.drop_table('writing_sessions')
    # ### end Alembic commands ###
