"""add login streak tracking

Revision ID: 166150ab8be6
Revises: 613c92bb18ed
Create Date: 2025-10-04 17:05:45.159857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166150ab8be6'
down_revision: Union[str, Sequence[str], None] = '613c92bb18ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_streaks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('login_streaks_pkey')),
    sa.UniqueConstraint('user_id', 'date', name='uq_login_streak_user_date')
    )
    op.create_index(op.f('login_streaks_date_idx'), 'login_streaks', ['date'], unique=False)
    op.create_index(op.f('login_streaks_id_idx'), 'login_streaks', ['id'], unique=False)
    op.create_index(op.f('login_streaks_user_id_idx'), 'login_streaks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('login_streaks_user_id_idx'), table_name='login_streaks')
    op.drop_index(op.f('login_streaks_id_idx'), table_name='login_streaks')
    op.drop_index(op.f('login_streaks_date_idx'), table_name='login_streaks')
    op.drop_table('login_streaks')
    # ### end Alembic commands ###
