"""add is_online

Revision ID: 7d6cd8f642f1
Revises: c55c63b0ce4e
Create Date: 2025-10-03 21:04:03.441530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6cd8f642f1'
down_revision: Union[str, Sequence[str], None] = 'c55c63b0ce4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with a server default so existing rows get a value, then drop default if undesired
    op.add_column('users', sa.Column('is_online', sa.Boolean(), server_default=sa.false(), nullable=False))
    # Optional: if you prefer no persistent default, uncomment the next line to drop default
    op.alter_column('users', 'is_online', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
