"""simplify online status to users.is_online

Revision ID: 925d2a6fba81
Revises: 0e62cdb61749
Create Date: 2025-10-04 17:18:19.842774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925d2a6fba81'
down_revision: Union[str, Sequence[str], None] = '613c92bb18ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_online column with default value first
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True, server_default=sa.text('FALSE')))
    
    # Update existing rows to set is_online = FALSE
    op.execute("UPDATE users SET is_online = FALSE WHERE is_online IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'is_online', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
