"""add vocabulary table

Revision ID: 5f671483eafa
Revises: 9686ac04a15a
Create Date: 2025-10-24 19:20:59.481666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f671483eafa'
down_revision: Union[str, Sequence[str], None] = '9686ac04a15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vocabulary_sets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vocabulary_sets_pkey'))
    )
    op.create_index(op.f('vocabulary_sets_id_idx'), 'vocabulary_sets', ['id'], unique=False)
    op.create_index(op.f('vocabulary_sets_user_id_idx'), 'vocabulary_sets', ['user_id'], unique=False)
    op.create_table('vocabulary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_set_id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], name=op.f('vocabulary_items_dictionary_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vocabulary_items_user_id_fkey')),
    sa.ForeignKeyConstraint(['vocabulary_set_id'], ['vocabulary_sets.id'], name=op.f('vocabulary_items_vocabulary_set_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vocabulary_items_pkey'))
    )
    op.create_index(op.f('vocabulary_items_dictionary_id_idx'), 'vocabulary_items', ['dictionary_id'], unique=False)
    op.create_index(op.f('vocabulary_items_id_idx'), 'vocabulary_items', ['id'], unique=False)
    op.create_index(op.f('vocabulary_items_user_id_idx'), 'vocabulary_items', ['user_id'], unique=False)
    op.create_index(op.f('vocabulary_items_vocabulary_set_id_idx'), 'vocabulary_items', ['vocabulary_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('vocabulary_items_vocabulary_set_id_idx'), table_name='vocabulary_items')
    op.drop_index(op.f('vocabulary_items_user_id_idx'), table_name='vocabulary_items')
    op.drop_index(op.f('vocabulary_items_id_idx'), table_name='vocabulary_items')
    op.drop_index(op.f('vocabulary_items_dictionary_id_idx'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('vocabulary_sets_user_id_idx'), table_name='vocabulary_sets')
    op.drop_index(op.f('vocabulary_sets_id_idx'), table_name='vocabulary_sets')
    op.drop_table('vocabulary_sets')
    # ### end Alembic commands ###
