"""add_dictionary_table

Revision ID: bf86fc3ed07c
Revises: 4bac18ee00e6
Create Date: 2025-09-13 19:31:46.785095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf86fc3ed07c'
down_revision: Union[str, Sequence[str], None] = '4bac18ee00e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('definitions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dictionary_pkey'))
    )
    op.create_index(op.f('dictionary_id_idx'), 'dictionary', ['id'], unique=False)
    op.create_index('ix_dictionary_definitions', 'dictionary', ['definitions'], unique=False)
    op.create_index('ix_dictionary_expression', 'dictionary', ['expression'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dictionary_expression', table_name='dictionary')
    op.drop_index('ix_dictionary_definitions', table_name='dictionary')
    op.drop_index(op.f('dictionary_id_idx'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
