"""add audio_url

Revision ID: fd89e0c3c16b
Revises: 920d11e66b6d
Create Date: 2025-11-24 20:45:16.547436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd89e0c3c16b'
down_revision: Union[str, Sequence[str], None] = '920d11e66b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_chat_messages', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaking_chat_messages', 'audio_url')
    # ### end Alembic commands ###
