"""remove users.is_online column

Revision ID: 613c92bb18ed
Revises: 63f168f827c8
Create Date: 2025-10-04 11:29:49.280994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613c92bb18ed'
down_revision: Union[str, Sequence[str], None] = '63f168f827c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
