"""Rename difficulty to level in speaking_sessions

Revision ID: 3b2cdc7c6c54
Revises: 5866a4774f30
Create Date: 2025-10-25 06:56:34.898613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2cdc7c6c54'
down_revision: Union[str, Sequence[str], None] = '5866a4774f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_sessions', sa.Column('level', sa.String(length=2), nullable=False))
    op.drop_index(op.f('speaking_sessions_difficulty_idx'), table_name='speaking_sessions')
    op.create_index(op.f('speaking_sessions_level_idx'), 'speaking_sessions', ['level'], unique=False)
    op.drop_column('speaking_sessions', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_sessions', sa.Column('difficulty', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('speaking_sessions_level_idx'), table_name='speaking_sessions')
    op.create_index(op.f('speaking_sessions_difficulty_idx'), 'speaking_sessions', ['difficulty'], unique=False)
    op.drop_column('speaking_sessions', 'level')
    # ### end Alembic commands ###
