"""fix model learning path

Revision ID: 8464fecc9266
Revises: 518d82311c75
Create Date: 2025-12-26 09:58:49.106731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8464fecc9266'
down_revision: Union[str, Sequence[str], None] = '518d82311c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_lesson_plans', 'lesson_content')
    op.drop_column('daily_lesson_plans', 'title')
    op.add_column('user_lesson_progress', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('user_lesson_progress', sa.Column('lesson_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'lesson_type')
    op.drop_column('user_lesson_progress', 'title')
    op.add_column('daily_lesson_plans', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('daily_lesson_plans', sa.Column('lesson_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
