"""Rename difficulty to level in writing_sessions

Revision ID: b81f2b34f66f
Revises: 3b2cdc7c6c54
Create Date: 2025-10-25 07:09:19.868830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b81f2b34f66f'
down_revision: Union[str, Sequence[str], None] = '3b2cdc7c6c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_sessions', sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False))
    op.drop_column('writing_sessions', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_sessions', sa.Column('difficulty', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), autoincrement=False, nullable=False))
    op.drop_column('writing_sessions', 'level')
    # ### end Alembic commands ###
