"""add column total word table set

Revision ID: b615fed74cdf
Revises: 5f671483eafa
Create Date: 2025-10-24 20:12:14.518849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b615fed74cdf'
down_revision: Union[str, Sequence[str], None] = '5f671483eafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary_sets', sa.Column('total_words', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary_sets', 'total_words')
    # ### end Alembic commands ###
