"""allow_null_updated_at_in_posts

Revision ID: 5df4b60126bd
Revises: 3f7ec4c57f2a
Create Date: 2025-08-30 12:36:01.533365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df4b60126bd'
down_revision: Union[str, Sequence[str], None] = '3f7ec4c57f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
