"""remove_title_from_posts

Revision ID: abc3b1fd3b9a
Revises: 5df4b60126bd
Create Date: 2025-08-30 19:57:19.043929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc3b1fd3b9a'
down_revision: Union[str, Sequence[str], None] = '5df4b60126bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
