name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          timeout: 30s
          script: |
            cd /home/ubuntu/aeiouly-be
            git pull origin main
            sudo systemctl restart aeiouly
            echo "Deployment completed successfully!"

